const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 12,
      description: 'high quality pant',
    },
    {
      name: 'Nike Linen Pant',
      slug: 'nike-linen-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 15,
      description: 'high quality pant',
    },
    {
      name: 'Nike Linen Trouser',
      slug: 'nike-linen-Trouser',
      category: 'Trouser',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 15,
      description: 'high quality pant',
    },
  ],
};

export default data;
